### ISSUE TITLE
Duplicated slack notification messages

### ISSUE THREAD

**Issue by yokawasa** [st-tech/gatling-operator#9]
## Issue
It's been observed that sometimes duplicated slack notification messages per a Gatling test run are sent.  It's not always but sometimes.

## How to reproduce the issue 

Again, it's not always but sometimes duplicated slack notification messages are sent while it's expected that a single slack message per a Gatling test run when you set notifyReport: true like this: 

```yaml
apiVersion: gatling-operator.tech.zozo.com/v1alpha1
kind: Gatling
metadata:
  name: gatling-sample01
spec:
  generateReport: true                              
  notifyReport: true                               
  cleanupAfterJobDone: true                   
```

## Expected behavior 

Single slack message ( NOT duplicate messages ) per a Gatling test run should be sent when you set notifyReport: true
